USE_LR_PARSER

prog

(* ======================================================================================================= *)
<prog>                 ::= <declaration>.

<declaration>          ::= "int" identifier
                         | "bool" identifier
                         | <initialization>.

<initialization>       ::= "int" identifier "=" integer
                         | "bool" identifier "=" boolean.           